### ISSUE TITLE
Add `ibm-cloud-cognitive` to Carbon Devtools

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#1178]
The Carbon devtools () are able to identify components in pages and provide useful information about them. This is not limited to Carbon components themselves, but can also handle components from other related packages (https://github.com/carbon-design-system/devtools/blob/base/packages/web-extension/src/globals/componentList.js), but this does not currently include the C&CS components.

Add the C&CS components to the Carbon devtools, as a useful functional aid for IBM product development teams.

As part of this, we need to figure out the best way to identify C&CS components live in a page. The Carbon, security and Cloud PAL components are identified just by a block class on the main element. Is that sufficient/satisfactory? If so, perhaps we should address the rather overdue question of our own package prefix, which is currently the rather anomalous "exp--", before adding our components to the devtools! Or should we use a different approach, such as some custom tag on the main element?

**Comment by SimonFinney** [comment]
- [ ] Add `ibm-cloud-cognitive` package to [Carbon Devtools repo](https://github.com/carbon-design-system/devtools)
- [ ] Deliver stable identification mechanism for browser extensions
- [ ] Understand and align on maintenance strategy with [Devtools contributors](https://github.com/carbon-design-system/devtools/graphs/contributors)
