### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Levinson1** [carbon-design-system/ibm-cloud-cognitive#134]
Pattern design documentation: https://pages.github.ibm.com/cdai-design/pal/patterns/notifications

Dev maintainer: Matt Gallo (@matthewgallo)

**Comment by matthewgallo** [comment]
## Tasks

- [ ] Initial review of design/existing code

### Working in experimental package

- [ ] Create a shell component which
  - [ ] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [ ] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [ ] Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.
- [ ] First engineering review/playback

### Continuing in experimental package

- [ ] Storybook - stories to cover design scenarios, story with long, min and
      max content, etc
- [ ] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [ ] Code to include prop-types with comments for automated DocGen
      documentation
- [ ] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

### Review and promote

- [ ] Design review
- [ ] Add design review issues addressed, issues raised or discounted.
- [ ] Engineering review - Submit PR to promote component to production package
- [ ] All engineering issues addressed, issues raised or discounted.

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/254 for initial work

**Comment by mauifrancis78** [comment]
@matthewgallo Ok finally got my Git up and working. Here are some points of feedback I see so far along with screen shots:

Spacing/padding (which I provided a screen for)
What happened to the bottom bar “view all” “settings icon”?
Individual notification dimiss controls
Read/unread states
Empty state spacing

![Notification active (click state)](https://user-images.githubusercontent.com/75501685/101216299-e2761e80-3644-11eb-96d1-813d6fc8f41c.png)

![Notification default](https://user-images.githubusercontent.com/75501685/101216301-e30eb500-3644-11eb-8550-b650c529383a.png)

![Notification hover](https://user-images.githubusercontent.com/75501685/101216302-e30eb500-3644-11eb-88cc-2e2933610b36.png)

![Notification_empty state](https://user-images.githubusercontent.com/75501685/101216826-d2127380-3645-11eb-80c5-1c518770c9a0.png)

**Comment by matthewgallo** [comment]
Thanks for the feedback @mauifrancis78! I just finished the first version of the side panel component and have more time to make these updates now. I'll let you know when they're complete

**Comment by matthewgallo** [comment]
Made design updates here https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/283

**Comment by andrea-gm** [comment]
@matthewgallo in the preview I'm seeing an unexpected horizontal scrollbar
<img width="394" alt="Screen Shot 2021-02-10 at 2 15 48 PM" src="https://user-images.githubusercontent.com/14081333/107579767-8088e680-6baa-11eb-8b0a-e4478b57ee50.png">

**Comment by matthewgallo** [comment]
Thanks for bringing this up @andrea-gm, I’ll take a look

**Comment by matthewgallo** [comment]
Should be fixed [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/334)

**Comment by andrea-gm** [comment]
@matthewgallo Minor detail, sorry I just noticed this while reviewing the scrollbar PR, but I think it would be nice to have the hover state cover the whole 1px line at the top. Otherwise it looks a little choppy.

Thoughts @mauifrancis78 ?

<img width="654" alt="Screen Shot 2021-02-11 at 11 57 29 AM" src="https://user-images.githubusercontent.com/14081333/107691665-96f17980-6c60-11eb-99ad-b52515d41e9e.png">

**Comment by mauifrancis78** [comment]
Not minor at all, in fact I think you are spot on! I agree 100%
 
Thanks,Maui FrancisDesign Principal  |  IBM Watson Data & AI  |  512.431.2654
 
 
----- Original message -----From: Andrea <notifications@github.com>To: carbon-design-system/ibm-cloud-cognitive <ibm-cloud-cognitive@noreply.github.com>Cc: mauifrancis78 <mfranci@us.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [carbon-design-system/ibm-cloud-cognitive] Notifications (#134)Date: Thu, Feb 11, 2021 2:02 PM 
 
@matthewgallo Minor detail, sorry I just noticed this while reviewing the scrollbar PR, but I think it would be nice to have the hover state cover the whole 1px line at the top. Otherwise it looks a little choppy.
Thoughts @mauifrancis78 ?

**Comment by matthewgallo** [comment]
Hey @andrea-gm and @mauifrancis78, the underline issue will be fixed with #343.

**Comment by dcwarwick** [comment]
## Review for release

### Readiness

- [ ] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [ ] A functioning component or components delivering those scenarios have been delivered and merged to master.
- [ ] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [ ] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [ ] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [ ] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [ ] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [ ] Components are functional components using hooks.
- [ ] Public components which produce DOM structures support className.
- [ ] Public components support a ref (via React.forwardRef).
- [ ] All significant DOM elements have meaningful classes.
- [ ] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [ ] No warnings, errors or log messages in the console.

### Standards

- [ ] No linter warnings or errors are produced.
- [ ] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [ ] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [ ] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [ ] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [ ] There is a set of test cases for the components.
- [ ] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [ ] The tests validate the behaviors and interactions defined in the design where practical.
- [ ] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [ ] No warnings, errors or log messages in the test output.

### Documentation

- [ ] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [ ] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [ ] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by andrea-gm** [comment]
@matthewgallo have you synced with Dejan Glozic about the notifications panel? I heard his team will implement their own for the global navigation bar (for one pak). So it might be good to share this with him and see what they can leverage. It may not make sense in the future to maintain two separate notification panels, so it'd be good to find a solution that works for one pak and for anyone else who may need it.

**Comment by dcwarwick** [comment]
NotificationsPanel has been released and we understand the situation. I think this epic can be closed. If there is further work to be done this can be addressed with a new issue.
