### ISSUE TITLE
About screen modal

### ISSUE THREAD

**Issue by Levinson1** [carbon-design-system/ibm-cloud-cognitive#148]
New pattern in need of code
https://pages.github.ibm.com/cdai-design/pal/patterns/about-modal/usage

[View about modal implementation](https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-aboutmodal--default)

Design Maintainer: Pascal Potvin (@pascal-potvin)
Dev Maintainer: Matt Gallo (@matthewgallo)

## Tasks

- [x] Initial review of design/existing code

### Working in experimental package

- [x] Create a shell component which
  - [x] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [x] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [x] Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.
- [x] First engineering review/playback

### Continuing in experimental package

- [x] Storybook - stories to cover design scenarios, story with long, min and
      max content, etc
- [x] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [x] Code to include prop-types with comments for automated DocGen
      documentation
- [x] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

**Comment by matthewgallo** [comment]
Hey @Levinson1, is there a design contact for this component?

**Comment by Levinson1** [comment]
Hey @matthewgallo . Designer for this one is @pascal-potvin .

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/187

**Comment by pascal-potvin** [comment]
This looks really good! A couple of small things here.

**Scroll fade**: The fade should be the exact same colour as the background, which goes from 100% opacity to 0% opacity. It seems to be currently set as black.

**Tabs:** They seem off in the Storybook example. We should be using the _default tabs_ and not the _container tabs_ 

![image](https://user-images.githubusercontent.com/38508793/99675370-23671400-2a45-11eb-90b6-ce8595ace3ca.png)

**Comment by matthewgallo** [comment]
Thanks for the review @pascal-potvin, I think the deployed storybook is using a different `carbon-components-react` version, where the Tab component had a class change. This is what it looks like with the correct version

![image](https://user-images.githubusercontent.com/10215203/99702959-81572400-2a64-11eb-93db-f8853fad7050.png)

I'll take a look at the `scroll fade` issue you mentioned 👍

**Comment by matthewgallo** [comment]
If you check out the main storybook, the tabs look ok. I think it was just that old storybook preview link, got messed up. See [here](https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-aboutmodal--with-technology-used-tab).

**Comment by lee-chase** [comment]
@matthewgallo you still need to adjust the fade color to move this into 'Release Review'

**Comment by matthewgallo** [comment]
Scroll gradient issue is fixed with this PR, https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/256

**Comment by dcwarwick** [comment]
## Review for release

### Readiness

- [ ] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [ ] A functioning component or components delivering those scenarios have been delivered and merged to master.
- [ ] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [ ] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [ ] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [ ] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [ ] The UI produced is accessible, responsive, translatable, cross-browser (Q: what browsers?), and responds to the currently set Carbon theme.
- [ ] Components are functional components using hooks.
- [ ] Public components which produce DOM structures support className.
- [ ] Public components support a ref (via React.forwardRef).
- [ ] All significant DOM elements have meaningful classes.
- [ ] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [ ] No warnings, errors or log messages in the console.

### Standards

- [ ] No linter warnings or errors are produced.
- [ ] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [ ] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [ ] Code is clear, maintainable and follows standard React practices. - [ ] Copyright header in every source file (js, css, scss etc.)

### Testing

- [ ] There is a set of test cases for the components.
- [ ] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [ ] The tests validate the behaviors and interactions defined in the design where practical.
- [ ] The tests achieve at least 80% coverage.
- [ ] No warnings, errors or log messages in the test output.

### Documentation

- [ ] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [ ] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [ ] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by dcwarwick** [comment]
@pascal-potvin Hi Pascal -- we're now reviewing this component for release readiness: could you please check whether the AboutModal component complies with your design and post a comment here to confirm or to identify issues? Thanks.

**Comment by dcwarwick** [comment]
Component reviewed and released.
