### ISSUE TITLE
Add Breadcrumb overflow component

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#181]
# Breadcrumb Overflow Content

## Details/Design

See https://www.carbondesignsystem.com/components/breadcrumb/usage/#overflow-content
 
Requried by #59 

## Design Maintainer(s)

- Owner/main maintainer(s)
- Second/backup maintainer(s)

## Tasks

- [x] Initial review of design/existing code

None that we are aware of.

### Working in experimental package

- [ ] Create a shell component which
  - [ ] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [ ] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [ ] Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.
- [ ] First engineering review/playback

### Continuing in experimental package

- [ ] Storybook - stories to cover design scenarios, story with long, min and
      max content, story to demonstrate right-to-left support, etc.
- [ ] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [ ] Code to include prop-types with comments for automated DocGen
      documentation
- [ ] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

### Review and promote

- [ ] Design review
- [ ] Add design review issues addressed, issues raised or discounted.
- [ ] Engineering review - Submit PR to promote component to production package
- [ ] All engineering issues addressed, issues raised or discounted.

**Comment by lee-chase** [comment]
Polina Olemskaia is picking this one up, assigned to myself in lieu of a github id.

**Comment by lee-chase** [comment]
Blocked: 
- Waiting on Carbon update including https://github.com/carbon-design-system/carbon/pull/7085 which could be two weeks as not included in 10.25.0.

**Comment by lee-chase** [comment]
Has runtime errors

![image](https://user-images.githubusercontent.com/15086604/101165827-3544db80-362f-11eb-9ed3-2417097da8fd.png)

**Comment by lee-chase** [comment]
Runtime errors have been addressed. Needs to update styling to reflect that of the Carbon PR, which appears to have stalled.

**Comment by lee-chase** [comment]
Unblocked copy styling of Carbon PR 7085

Raised the following issue for the removal of PRs and unblocking this issue.
https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/330

**Comment by lee-chase** [comment]
I think this is more or less done for the page header. Need to check errors posted above and arrange a design review.

**Comment by lee-chase** [comment]
Tests added with #573

**Comment by lee-chase** [comment]
Styling replaced by Carbon styling from 10.32

**Comment by lee-chase** [comment]
Closing as not a public component and tests at 100% coverage.
