### ISSUE TITLE
Toolbar that shrinks to overflow

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#182]
# ToolbarWithOverflow

## Brief description

Toolbars like other components can have space restricted. This toolbar should collapse to a single overflow menu if there is not enough room for it to fit entirely, or on a property value being set.

Required by #59

## Details

See responsive examples here

https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/59#issuecomment-717534680

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Owner/main maintainer(s)
- Second/backup maintainer(s)

## Tasks

- [x] Initial review of design/existing code

### Working in experimental package

- [x] Create a shell component which
  - [x] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [x] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [ ] ~~Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.~~ Only used by page header
- [x] First engineering review/playback

### Continuing in experimental package

- [x] Storybook - stories to cover design scenarios, story with long, min and
      max content, story to demonstrate right-to-left support, etc.
- [x] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [x] Code to include prop-types with comments for automated DocGen
      documentation
- [x] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

### Review and promote

- [x] Design review
- [x] Add design review issues addressed, issues raised or discounted.
- [ ] Engineering review - Submit PR to promote component to production package
- [ ] All engineering issues addressed, issues raised or discounted.

**Comment by lee-chase** [comment]
Duplicate or customisation of #38 ?

**Comment by lee-chase** [comment]
Similar overflow behaviour to #32 and as a result should probably be on hold in the short term to see an update from the existing tag overflow code. Required by #59

**Comment by andrea-gm** [comment]
@lee-chase is this on hold or in progress? If on hold, could we move things out of "In progress"?

**Comment by lee-chase** [comment]
Needs tests and documentation before moving forward.

Needs an update to use labels instead of tooltips in overflow. Will address today.

**Comment by lee-chase** [comment]
Now users labels just needs tests

**Comment by lee-chase** [comment]
Tests added with #338
