### ISSUE TITLE
Tearsheet

### ISSUE THREAD

**Issue by moores2** [carbon-design-system/ibm-cloud-cognitive#183]
# Tearsheet component

Dev maintainer: Dave Clark (@dcwarwick)

## Brief description

The Tearsheet component facilitates rich modal interactions such as resource creations that require multiple steps. It is akin to a dialog that is anchored to the bottom of the viewport. They come in 2 sizes, narrow and wide, each with specific layouts. They can be stacked, facilitating nested interactions. 

![image](https://user-images.githubusercontent.com/6977424/97885467-4f815600-1d1f-11eb-85e3-699446392d78.png)

## Details

[Link to INTERIM Design](https://ibm.ent.box.com/notes/713596972705?s=0fvfln65s2oh0mqrducnqknz29jead23)

### Links to other materials

The Tearsheet is a pre-req for issue #52. 

## Design Maintainer(s)

- Owner/main maintainer(s): Mitchell Bernstein 
- Second/backup maintainer(s)

## Tasks

- [x] Initial review of design/existing code

### Working in experimental package

- [ ] Create a shell component which
  - [x] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [x] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [x] Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.
- [ ] First engineering review/playback

### Continuing in experimental package

- [ ] Storybook - stories to cover design scenarios, story with long, min and
      max content, story to demonstrate right-to-left support, etc.
- [x] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [x] Code to include prop-types with comments for automated DocGen
      documentation
- [ ] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

### Review and promote

- [ ] Design review
- [ ] Add design review issues addressed, issues raised or discounted.
- [ ] Engineering review - Submit PR to promote component to production package
- [ ] All engineering issues addressed, issues raised or discounted.

**Comment by mitchellbernstein** [comment]
Pattern guidance for tearsheet published: https://pages.github.ibm.com/cdai-design/pal/components/tearsheet/usage

**Comment by gentryb** [comment]
@lee-chase  CPD (on-prem) is scoping priorities for 4.0 release. Several experience are looking to utilize the tearsheet component. Do you have a ball park time-line for when it will be completed?

**Comment by moores2** [comment]
> @lee-chase CPD (on-prem) is scoping priorities for 4.0 release. Several experience are looking to utilize the tearsheet component. Do you have a ball park time-line for when it will be completed?

The tearsheet is currently under active development. Almost all of the functionality is already available in the version in the experimental package. There is work to do on keyboard enabling, docs, and automated tests, prior to it being ready for design and engineering review. I hope it will be ready for those reviews in a couple of weeks, then it depends on the outcome as to how soon it can be promoted to production.

**Comment by dcwarwick** [comment]
## Review for release

### Readiness

- [ ] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [ ] A functioning component or components delivering those scenarios have been delivered and merged to master.
- [ ] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [ ] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [ ] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [ ] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [ ] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [ ] Components are functional components using hooks.
- [ ] Public components which produce DOM structures support className.
- [ ] Public components support a ref (via React.forwardRef).
- [ ] All significant DOM elements have meaningful classes.
- [ ] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [ ] No warnings, errors or log messages in the console.

### Standards

- [ ] No linter warnings or errors are produced.
- [ ] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [ ] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [ ] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [ ] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [ ] There is a set of test cases for the components.
- [ ] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [ ] The tests validate the behaviors and interactions defined in the design where practical.
- [ ] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [ ] No warnings, errors or log messages in the test output.

### Documentation

- [ ] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [ ] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [ ] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.
