### ISSUE TITLE
Data table extension: batch actions

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#1985]
# Data table extensions: batch actions

## Brief description
This issue will focus on the batch actions data table extension.

- [ ] Add Select all button in data table toolbar
- [ ] Add More button when more than 4 actions present in the toolbar
    - This should become an overflow menu at smaller screen sizes

## Details
[Design specs](https://ibm.box.com/s/mx7wmqisvnhyw9u6hl1oy0yhbu1nhfqj)

This is partially implemented, but we are missing select all across all pages. Our current implementation includes this in a dropdown that shows “Select all on page” and “Select all.” The updated implementation should use a **select all button in the toolbar**.

![image.png](https://images.zenhubusercontent.com/6109a215337f0517b2f0e02f/738f8cba-afa0-4114-9f21-80864ff4df0e)

Additionally, we need to include a More button if more than 4 actions are present in the data table toolbar. On smaller screen sizes, this should become an overflow menu.

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Marion Brülls
- Virginia Nicholson
- Mitchell Bernstein

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by elycheea** [comment]
@holmansze I spoke with @marion-bruells for clarification when we opened this issue. The behavior from WKC was changed in the PAL guidance.

Reading the Box note again, I believe the Select all button would only be used/recommended in cases with more than 100 rows? So the option to **Select all** would only appear after at least one item is selected _if_ there’s more than 100 rows.

We do currently have [Select all from all pages](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--select-items-in-all-pages) — are you recommending to remove select from all pages entirely for paginated tables? @holmansze @marion-bruells

**Comment by holmansze** [comment]
@elycheea 

Saw the storybook, thanks.

I think we can keep the "select all on page" and "select all" options in the column header checkbox. I actually like the fact that it offers the 2 options clearly. We can leave it to the consumer to decide if they can support "select all" based on the nature of the application. For example, if the application does not have a paginated backend API and it always fetches all records, it makes sense to support both "select all" and "select all on page". For an application that has a paginated backend API (and potentially handling high volume of data), the consumer would probably just support "select all on page".

I would recommend not adding the explicit "Select all" button in the table toolbar area. The column header checkbox already handles that and it clearly shows the 2 select options.

**Comment by matthewgallo** [comment]
@marion-bruells is the "Select all" button with the left hand placement something we can address later on given the discussion over slack, [here](https://ibm-casdesign.slack.com/archives/C2K6RFJ1G/p1660232248472599). Everything else in the batch action designs is included in the current component.

**Comment by matthewgallo** [comment]
We previously included an implementation [here](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--select-items-in-all-pages) which included an overflow menu allowing for selecting all. Is this something we want to still keep?

**Comment by marion-bruells** [comment]
@matthewgallo no that one needs to be replaced. We shouldn’t have this overflow menu anymore, since it brings some issues in spacing and alignment. That pattern came from WKC but got reworked by PAL to simplify and avoid any extra space in the column header which this overflow button needs. It should be adjusted with this new guidance.

**Comment by elycheea** [comment]
@allcontributors add @marion-bruells for design
