### ISSUE TITLE
Data table extension: Filtering > Filter panel

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2252]
# Data table extension: Filtering

## Brief description

Part of #2069 

## Details

[Link to design](https://pages.github.ibm.com/cdai-design/pal/components/data-table/filters#filter-panel)
- [Styling and specs](https://pages.github.ibm.com/cdai-design/pal/components/data-table/filters#styling)

There’s currently already a story for `Left panel` — this story can be updated for `Filter panel`

- Filter panel should be collapsed by default ([expand and collapse](https://pages.github.ibm.com/cdai-design/pal/components/data-table/filters#expand-and-collapse))
   - [ ] Filter button should open filter panel
   - [ ] X should close filter panel
   - [ ] Filter trigger disabled in empty state but enabled with no results
- Filter panel should accept and support**
   - accordions
   - search filters (fixed when scrolling if used)
   - categories
   - counts
   - view all
- If using batch filters, action buttons should fix at to bottom of the panel
- Make sure to test filter with various amounts of content both before and after filtering

** for the filter children — will largely reuse work that @AlexanderMelox is working on for #2251. Work with him to mock the structure as needed to minimize duplicate efforts.

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Shelley Dignum
- Ashley Bock

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?
