### ISSUE TITLE
In-page navigation component

### ISSUE THREAD

**Issue by chloepoulterdesign** [carbon-design-system/ibm-cloud-cognitive#265]
# In-page navigation component

## Brief description

We've had a few requests in the last week or so for code for the in-page navigation component. 
It is already implemented as part of the (old) create flow by CP4I. 
It is also  implemented independently of the create flow by both Event Streams and MQ teams. 

## Details

[Link to Design](https://pages.github.ibm.com/cdai-design/pal/wip/in-page-navigation/usage/) 
More design work can be made available if needed, however I'm hoping that since it is already widely implemented, we can use implemented code.

Happy to consult more, especially on the two implementation methods (anchor links vs pages) that are explained in the link above.

## Design Maintainer(s)

- Owner/main maintainer(s): Chloe Poutler
- Second/backup maintainer(s): Peter Loveland

Recent expressions of interest in consuming it: Felix Ba, Mitchell Bernstein, Matas Bartosevicius

## Tasks

- [ ] Initial review of design/existing code

### Working in experimental package

- [ ] Create a shell component which
  - [ ] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [ ] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [ ] Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.
- [ ] First engineering review/playback

### Continuing in experimental package

- [ ] Storybook - stories to cover design scenarios, story with long, min and
      max content, story to demonstrate right-to-left support, etc.
- [ ] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [ ] Code to include prop-types with comments for automated DocGen
      documentation
- [ ] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

### New production dependencies

- [ ] Verify the dependency has previously been
      [pedigree reviewed](https://pedigree-service.wdc1a.cirrus.ibm.com)
- [ ] Verify the dependency
      [doesn't contain any vulnerabilities](https://snyk.io/vuln)
- [ ] Verify the dependency [bundle size](https://bundlephobia.com) is
      acceptable
- [ ] Verify the dependency is [actively maintained](https://www.npmtrends.com)

### Review and promote

-
- [ ] Design review
- [ ] Add design review issues addressed, issues raised or discounted.
- [ ] Engineering review - Submit PR to promote component to production package
- [ ] All engineering issues addressed, issues raised or discounted.

**Comment by chloepoulterdesign** [comment]
Today I found that carbon have a very similar component included in their UI shell example in their React storybook.
https://react.carbondesignsystem.com/?path=/story/ui-shell--fixed-side-nav
It's pretty much identical, expect their implementation is instead of a left bar navigation - here's an illustration:
![image](https://user-images.githubusercontent.com/47979346/102076895-6035e900-3e00-11eb-856f-b10723a1ea02.png)

**Comment by lee-chase** [comment]
@chloepoulterdesign there is no black left bar in Carbon React but outside of a styling is it really different from the side rail?

https://react.carbondesignsystem.com/?path=/story/ui-shell--side-nav-rail-w-header
