### ISSUE TITLE
Rename InlineEdit to EditInPlace

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2866]
# EditInPlace

## Brief description

The naming of inline edit should be updated to `EditInPlace`. Discussion brought up originally in [PAL repo](https://github.ibm.com/CDAI-design/pal/issues/737) by @lee-chase 

## Details

[Link to Design]() [Link to example or existing component]()

- [ ] Expose `InlineEdit` as both `InlineEdit` and `EditInPlace`
- [ ] Add deprecation warning to InlineEdit

- [ ] Should default to new name v2, and feature flag in v1.

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Shelley Dignum @sdignum

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by elycheea** [comment]
@lee-chase Seems like consensus is `EditInPlace`, which was one of your original suggestions. Let’s go with that. 🚀
