### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#30]
[**Link to design**](https://www.carbondesignsystem.com/community/patterns/import-pattern/)

Maintainers: [Vikki Paterson](https://github.com/vikkipaterson) , [Chloe Poulter](https://github.com/chloepoulterdesign)

Dev Maintainer: @davidmenendez 

Catalog number: 12

## Tasks

- [x] Initial review of design/existing code

## Release reviewer(s)

- @matthewgallo 
- @sydrosa 

### Working in experimental package

- [x] Create a shell component which
  - [x] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [x] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [x] Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.
- [x] First engineering review/playback

### Continuing in experimental package

- [x] Storybook - stories to cover design scenarios, story with long, min and
      max content, etc
- [x] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [x] Code to include prop-types with comments for automated DocGen
      documentation
- [x] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

### Review and promote

- [x] Design review
- [x] Add design review issues addressed, issues raised or discounted.
- [x] Engineering review - Submit PR to promote component to production package
- [x] All engineering issues addressed, issues raised or discounted.

**Comment by carrenelloyd** [comment]
[**Link to design**](https://www.carbondesignsystem.com/community/patterns/import-pattern/)

Maintainers: [Vikki Paterson](https://github.com/vikkipaterson) , [Chloe Poulter](https://github.com/chloepoulterdesign)

Catalog number: 12

**Comment by SimonFinney** [comment]
@carrenelloyd Would you know if there's redlines or existing code available for this?

**Comment by SimonFinney** [comment]
Existing code - https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/production-ready-ide-importing-importing--importing-multiple-files

**Comment by lee-chase** [comment]
Initial Dev review.

@vikkipaterson @chloepoulterdesign this looks very much like this with various container options and action buttons.

https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/production-ready-ide-importing-uploading--extension-validation

Are the various container patterns and action buttons part of this issue or is it simply the component as found in the link above?

**Comment by chloepoulterdesign** [comment]
Hi all, there are a few moving pieces with import:
- We're going to deprecate the [file upload component at PAL](https://pages.github.ibm.com/cdai-design/pal/components/file-uploader/usage) in favour of the Carbon drag & drop file uploader - tracking for this is [here](https://github.ibm.com/CDAI-design/pal/issues/303)
- There is some work going on in the background to the Carbon file uploader to improve the UX for single file upload
- In my view, the job of the import pattern is to add the URL field part and some validation that isn't offered by the file uploader. We don't have the bandwidth to add to the PAL documentation to explain validation right now.
- The code in the storybook looks vaguely correct, and the guidance in the pattern documentation explains that the code can then be put into side panels, modals or full pages. The examples in the PAL documentation show cancel/next buttons which are there because the import example in the images is contained inside a create flow. As far as I am concerned there is no immediate further work required to the code.

**Comment by lee-chase** [comment]
Assigned to David as it's another modal.

**Comment by lee-chase** [comment]
Hi @davidmenendez it might be useful for you to review https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/178

**Comment by davidmenendez** [comment]
Ready for design review @chloepoulterdesign @vikkipaterson 

I have a small PR up currently that fixes some a typo in the story that i'm waiting to get merged, which should be merged shortly, but aside from that it's ready for review.

**Comment by chloepoulterdesign** [comment]
Thanks @davidmenendez 
Am I reviewing the "IdeImport" or the "Import modals"?
![image](https://user-images.githubusercontent.com/47979346/100863149-07736180-348c-11eb-99b2-e70cf518eb26.png)

**Comment by davidmenendez** [comment]
@chloepoulterdesign apologies. I meant to link it directly in my last comment. it's the Experimental version. https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-importmodal--standard

**Comment by Levinson1** [comment]
@chloepoulterdesign can you provide a final review before the end of the week?

**Comment by chloepoulterdesign** [comment]
Thanks @davidmenendez , sorry I should have guessed that.

Here's my review.
In modals, we only allow single file upload/import, and therefore, the input fields should be disabled once a user has selected a file:
![image](https://user-images.githubusercontent.com/47979346/100991895-6a77fd80-354b-11eb-9fad-f370b3d875f3.png)
In the view above, the `1 / 1 files uploaded` line above the imported file is also missing. 

I think this is what it should look like when a file has been selected:
![image](https://user-images.githubusercontent.com/47979346/100992059-a01ce680-354b-11eb-997e-1334825c064b.png)

Finally, [Carbon guidance](https://www.carbondesignsystem.com/components/modal/usage#alignment) says that there should be a ~20% padding on text on the right side in a modal, so there should be a bit of a gap on the right side of this text. 
![image](https://user-images.githubusercontent.com/47979346/100992253-dd817400-354b-11eb-8906-78f5e7b4aa34.png)

**Comment by davidmenendez** [comment]
@chloepoulterdesign design feedback has been been applied. please review. https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-importmodal--standard

**Comment by chloepoulterdesign** [comment]
Thanks @davidmenendez 

I think issue ① is still there - when I've selected a file, the file upload drop area is still enabled - I would expect it to be disabled once I've selected the file.
![image](https://user-images.githubusercontent.com/47979346/103762661-9a199a00-5010-11eb-8fa5-2c39ada3533c.png)
I would expect it to look like this styling in the disabled state:
![image](https://user-images.githubusercontent.com/47979346/103763097-422f6300-5011-11eb-90b4-5641f7c6b5d8.png)

Otherwise, looks fantastic, thanks so much!

**Comment by davidmenendez** [comment]
ahh i see. this is a quick fix. i'll have this done in a few minutes 👍

**Comment by davidmenendez** [comment]
@chloepoulterdesign when you get a chance can you please re-review. thank you!

**Comment by chloepoulterdesign** [comment]
LGTM! 🙌🎉

**Comment by davidmenendez** [comment]
bump

**Comment by sydrosa** [comment]
## Review for release

### Readiness

- [ ] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [ ] A functioning component or components delivering those scenarios have been delivered and merged to master.
- [ ] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [ ] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [ ] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [ ] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [ ] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [ ] Components are functional components using hooks.
- [ ] Public components which produce DOM structures support className.
- [ ] Public components support a ref (via React.forwardRef).
- [ ] All significant DOM elements have meaningful classes.
- [ ] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [ ] No warnings, errors or log messages in the console.
- [ ] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js.

### Standards

- [ ] No linter warnings or errors are produced.
- [ ] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [ ] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [ ] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [ ] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [ ] There is a set of test cases for the components.
- [ ] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [ ] The tests validate the behaviors and interactions defined in the design where practical.
- [ ] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [ ] No warnings, errors or log messages in the test output.

### Documentation

- [ ] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [ ] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [ ] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.
