### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by Levinson1** [carbon-design-system/ibm-cloud-cognitive#301]
# Name of component or pattern - Cards

## Brief description - Cards group related pieces of information and invite the user to take action on the content. The user should be able to attain a quick overview of relevant and actionable content. Cards have a limited set of actions launched from them; this creates a singular focus for the user. 

Add a brief description.

## Details

https://pages.github.ibm.com/cdai-design/pal/components/card/overview

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Owner/main maintainer(s) - Johanna Koval
- Second/backup maintainer(s) - Kacie Eberhart, Pascal Potvin

## Tasks

- [x] Initial review of design/existing code

### Working in experimental package

- [x] Create a shell component which
  - [x] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [x] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [x] Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.
- [x] First engineering review/playback

### Continuing in experimental package

- [x] Storybook - stories to cover design scenarios, story with long, min and
      max content, story to demonstrate right-to-left support, etc.
- [x] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [x] Code to include prop-types with comments for automated DocGen
      documentation
- [x] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

### New production dependencies

- [x] Verify the dependency has previously been
      [pedigree reviewed](https://pedigree-service.wdc1a.cirrus.ibm.com)
- [x] Verify the dependency
      [doesn't contain any vulnerabilities](https://snyk.io/vuln)
- [x] Verify the dependency [bundle size](https://bundlephobia.com) is
      acceptable
- [x] Verify the dependency is [actively maintained](https://www.npmtrends.com)

### Review and promote

-
- [x] Design review
- [x] Add design review issues addressed, issues raised or discounted.
- [x] Engineering review - Submit PR to promote component to production package
- [ ] All engineering issues addressed, issues raised or discounted.
