### ISSUE TITLE
Create a non-experimental release of the ibm-cloud-cognitive

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#366]
- [x] Reorganise the repo into a single component source without 'experimental'.
- [ ] Change the package prefix to something other than 'exp' (what?).
- [x] Create a dummy forwarding wrapper at @carbon/ibm-cloud-cognitive-experimental (keeping 'exp' prefix and enable all components, and be marked deprecated).
- [x] Set up a review checklist to review components that are ready for release.
- [x] Provide a way to know which components are fully reviewed and released.
- [x] Review AboutModal in order to review the review checklist.
- [x] Complete review of AboutModal and marked as released.
- [ ] Review Tearsheet
- [ ] Complete review of Tearsheet and marked as released.
- [ ] Review Page header
- [ ] Complete review of Page header and marked as released.
- [ ] Review Cards
- [ ] Complete review of Cards and marked as released.
- [ ] Review Side panel
- [ ] Complete review of Side panel and marked as released.
- [ ] Review Create: tearsheet
- [ ] Complete review of Create: tearsheet and marked as released.
- [ ] Review Status icons
- [ ] Complete review of Status icons and marked as released.
- [ ] Review User profile images
- [ ] Complete review of User profile images and marked as released.
- [ ] Review Create: modal
- [ ] Complete review of Create: modal and marked as released.
- [ ] Review Create: side panel
- [ ] Complete review of Create: side panel and marked as released.
- [ ] Review Web terminal
- [ ] Complete review of Web terminal and marked as released.
