### ISSUE TITLE
Advanced filtering

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#407]
# Advanced filtering

## Brief description

Advanced search can be used when the user requires to search and filter a list of items by choosing more than one filter from multiple filter categories. This pattern is especially useful when the number of items within each category is dynamic, such as filtering a table, by a user or user defined tags.

There is a component for this already under "Legacy" -> "CDAI". It needs to be evaluated, updated if needed, and moved to "Cloud & Cognitive".

## Details

[Link to Design](https://pages.github.ibm.com/cdai-design/pal/patterns/advanced-filtering/usage)

[Existing component](https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/under-construction-ide-filter--default-example)

## Design Maintainer(s)

- Tom Solomon

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Cloud and Cognitive package

- [ ] Have reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [reviewer guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/REVIEWERS_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?
