### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#408]
# Remove

## Brief description

“Removing” is an action that moves information from one location to another. Removal can be both destructive and non-destructive. “Deletion” is the most common type of removal and is destructive.

## Details

[Link to Design](https://www.carbondesignsystem.com/community/patterns/remove-pattern/)

## Design Maintainer(s)

- @vikkipaterson 

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Cloud and Cognitive package

- [ ] Have reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [reviewer guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/REVIEWERS_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by andrea-gm** [comment]
Ugh. Ignore me. This already exists and is coded lol. Closing.
