### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#409]
# Saving

## Brief description

Preventing the loss of activity. Saving can be automatic or manual.

There is existing code for both auto-save and manual. The need here is to evaluate the components, update if needed, and move to "Cloud & Cognitive".

## Details

[Link to Design](https://pages.github.ibm.com/cdai-design/pal/patterns/saving/usage)
[Link to existing component](https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/under-construction-ide-saving--auto-save)

## Design Maintainer(s)

- @vikkipaterson 
- Chloe Poulter

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Cloud and Cognitive package

- [ ] Have reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [reviewer guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/REVIEWERS_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by davidmenendez** [comment]
based on the latest feedback I'm good to start prepping this for release review

<img width="505" alt="Screen Shot 2021-04-09 at 10 13 26 AM" src="https://user-images.githubusercontent.com/6370760/114201940-55a5df00-991c-11eb-98a6-e85a7daf42ff.png">

**Comment by dcwarwick** [comment]
## Review for release

### Readiness

- [ ] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [ ] A functioning component or components delivering those scenarios have been delivered and merged to master.
- [ ] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [ ] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [ ] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [ ] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [ ] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [ ] Components are functional components using hooks.
- [ ] Public components which produce DOM structures support className.
- [ ] Public components support a ref (via React.forwardRef).
- [ ] All significant DOM elements have meaningful classes.
- [ ] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [ ] No warnings, errors or log messages in the console.
- [ ] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js.

### Standards

- [ ] No linter warnings or errors are produced.
- [ ] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [ ] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [ ] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [ ] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [ ] There is a set of test cases for the components.
- [ ] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [ ] The tests validate the behaviors and interactions defined in the design where practical.
- [ ] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [ ] No warnings, errors or log messages in the test output.

### Documentation

- [ ] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [ ] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [ ] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.
