### ISSUE TITLE
Edit

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#53]
Catalog # 6

[Link to Design](https://www.carbondesignsystem.com/community/patterns/edit-pattern/)

**Maintainers**
Vikki Paterson, Chloe Poulter

## Tasks

- [ ] Initial review of design/existing code

### Working in experimental package

- [ ] Create a shell component which
  - [ ] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [ ] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [ ] Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.
- [ ] First engineering review/playback

### Continuing in experimental package

- [ ] Storybook - stories to cover design scenarios, story with long, min and
      max content, etc
- [ ] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [ ] Code to include prop-types with comments for automated DocGen
      documentation
- [ ] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

### Review and promote

- [ ] Design review
- [ ] Add design review issues addressed, issues raised or discounted.
- [ ] Engineering review - Submit PR to promote component to production package
- [ ] All engineering issues addressed, issues raised or discounted.

**Comment by lee-chase** [comment]
@vikkipaterson can you comment on the status of the design. @maciecorran marked this as 'status:refining'

**Comment by vikkidpaterson** [comment]
I think this may be affected by the updates being made to create because where possible / necessary edit should reflect the create process.

**Comment by andrea-gm** [comment]
https://github.ibm.com/ibmcloud/pal/issues/3706

**Comment by chloepoulterdesign** [comment]
Update to the related design work Andrea mentions:
We are looking at the edit pattern for a "V2" much as the Create Pattern has recently been revisited. It's going to be a holistic effort to capture new requirements and use cases we didn't foresee before. It will also pick up new visual styling from the create pattern where relevant. We're in early stages at the moment, collecting examples across C&CS - so I would very conservatively put an ETA of Aprile/May on design completion.
