### ISSUE TITLE
Empty states

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#54]
Catalog # 7

[Link to Design ](https://pages.github.ibm.com/cdai-design/pal/patterns/empty-state/usage)

**Maintainer**
Vikki Paterson

**Dev Maintainer**
@matthewgallo 

https://github.com/carbon-design-system/ibm-cloud-paks/projects/2#card-45884682

[View empty states implementation](https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-emptystate--default)
## Tasks
- [x] Initial review of design/existing code

### Working in experimental package
- [x] Create a shell component which
  - [x] Create ComponentName/ComponentName.js component file that renders props in raw form (no styling or sub components, plain text OK)
  - [x] Adds prop-types with comments for DocGen to ComponentName/ComponentName.js
  - [x] Add Doc file e.g. ComponentName.mdx with a brief description of the component.
- [x] First engineering review/playback
### Continuing in experimental package
- [x] Storybook - stories to cover design scenarios, story with long, min and
      max content, etc
- [x] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [x] Code to include prop-types with comments for automated DocGen
      documentation
- [x] Tests  (written in React Test Library) to cover behavior from the documented in the components mdx file.
### Review and promote
- [ ] Design review
- [ ] Add design review issues addressed, issues raised or discounted.
- [ ] Engineering review - Submit PR to promote component to production package
- [ ] All engineering issues addressed, issues raised or discounted.

**Comment by lee-chase** [comment]
@vikkipaterson can you comment on the status of the design it was marked as 'status: refining' by @carrenelloyd

**Comment by lee-chase** [comment]
Dev thoughts
This appears to be a redesign of https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/production-ready-ide-empty-state-component--default

@vikkipaterson I am a bit confused by the design. When describing sizes it shows a flow of image, title, description with optional CTA button below. Then when it moves to describe empty state types it shows sub-text, title, image.

Lift and shift with some styling tweaks. 

Clarify with @vikkipaterson whether a single call to action is permissible. The current implementation allows for an array of links https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/production-ready-ide-empty-state-component--default

**Comment by vikkipaterson** [comment]
@lee-chase Hey Lee.  I wasn't aware of the empty states pattern changing from what was previously built however it looks like the pattern has been updated slightly to only show examples of empty states in cards / tiles in the types descriptions 
which is a little misleading! Can you see who last updated the page?

**Comment by matthewgallo** [comment]
See https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/159

**Comment by lee-chase** [comment]
@vikkipaterson this shows recent updates https://github.ibm.com/CDAI-design/pal/commits/master/src/pages/patterns/empty-state/usage.mdx

If you are happy it reflects https://pages.github.ibm.com/cdai-design/pal/patterns/empty-state/usage can we move it to 'Release Review'?

**Comment by vikkipaterson** [comment]
LGTM I wold say it can move to Release review.  Probably worth getting a visual designer to give it a once over as a final check.

**Comment by andrea-gm** [comment]
Is there a plan to implement empty states for data tables? Currently, each dev team is implementing in their own unique way.

**Comment by dcwarwick** [comment]
Closed by #779
