### ISSUE TITLE
Page Header

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#59]
## Issue description

Catalog # 16

Design maintainer: Cameron Calder
Dev maintainer: Lee Chase

[Link to Design ](https://pages.github.ibm.com/cdai-design/pal/components/page-header/usage/)
Replace existing design with new design below

[Link to Design Issue](https://github.ibm.com/CDAI-design/pal/issues/102)

[Working code](https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/production-ready-ide-navigation-components-ide-page-header-component--with-breadcrumb-heading-subtitle-and-tabs-properties)

[View page header implementation](https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-pageheader--all-attributes-set)

## Implementation tasks

- [x] Evaluate existing components. Is it a good starting point for the new header.
- [x] Boolean property to control background appearance
- [x] Breadcrumb and action bar (optional, jsx) - Array of BreadcrumbItem
- [x] Title (optional, prop string 56) and Actions (optional, jsx)
- [x] Subtitle/description area (string, optional)
- [x] Available space (optional, jsx)
- [x] Tabs / Content switcher (optional slot, jsx) (story to include content of tabs)
- [x] Stories (1 story per every design example)
- [x] Tests
  - [x] Convert tests to React Test Library
- [x] Documentation
  - [x] Fix scroll behaviour in Doc page.
- [x] Outstanding issues:
  - [x] No easing when the primary action buttons jump to action bar during scrolling.
  - [x] Primary action buttons possibly jump too early - perhaps they should jump just as they hit the action bar and not before.
  - [x] In this [story](http://localhost:3000/?path=/story/experimental-pageheader--with-background-breadcrumbitems-title-pageactions-tags)  when you scroll the tags off the page it leaves too much whitespace below the primary page action buttons.
  - [x] The title wraps and it should not.
  - [x] The title should be limited to 56 chars and truncated and an ellipse added if it's longer that that, with the full text in the browser hover tooltip. Could be hard because of localisation.

## Review items
- [x] Ready for initial review.
- [x] Fix background color on load (maybe use ResizeObserver package)
- [x] Review responsive behaviour.

## Design review
- [x] Ensure spacing between type and objects matches spacing tokens used in design specs under the Structure section below
- [x] Tabs should be offset 16 to the left so the type in the tabs aligns with the Page title
- [x] 'Without Background BreadcrumbItems Title' shouldn't load with a background
- [x] Breadcrumbs font should be size `$label-01`
![Artboard Copy](https://user-images.githubusercontent.com/50155706/99822211-8e354f80-2b18-11eb-81cf-e2c37908cd1c.png)
- [x] When the page header with no background transitions to the condensed breadcrumb bar, fade the background in with the speed of the scroll instead of the hard cut in
- [x] When there is an Actionbar visible, wait until after the buttons scrolls under the Actionbar to animate in the buttons within the Actionbar area. Button fade animation should be: `button fade-in & fade-out transition = motion(entrance, productive) / cubic-bezier(0, 0, 0.38, 0.9) $transition—base`
- [x] Divider line underneath the Actionbar should extend the full width
- [x] 'With Background Breadcrumbitems Actionbar': Should include the 'Page title' at the end of the breadcrumb
- [x] 'Long Values And Many Items': Match guidance for 'Page lengths' and 'Responsive behavior'
- [x] If there is no page header background, there should be a `$layout-03` spacer between the page title and the page content
![Artboard](https://user-images.githubusercontent.com/50155706/99821479-b7a1ab80-2b17-11eb-8717-f608c6eccf32.png)
- [x] When it’s just the breadcrumb and no breadcrumb/action bar, it should be `$spacing-02` between the breadcrumbs and the page title
![Artboard Copy 3](https://user-images.githubusercontent.com/50155706/99822561-f97f2180-2b18-11eb-84e3-efcebd34eaca.png)
- [x] Remove the **With Background Breadcrumbitems Title  Pageactions Content Switcher** example.  Upon further discussion with designers across the org, the content switcher is not a component we want to advertise as proper within the page header.
- [ ] The space between the status & page content should be `$layout-03`
![Artboard Copy 6](https://user-images.githubusercontent.com/50155706/99823882-8a0a3180-2b1a-11eb-81ea-35a1abff5420.png)
- [x] **With Background Breadcrumbitems Title Pageactions Tags**: Tags are offset from the left. The space between the title and tags should also be `$spacing-05`
![Artboard Copy 7](https://user-images.githubusercontent.com/50155706/99849255-dc5e4900-2b40-11eb-9d70-7b1da98c8578.png)
- [x] **With Background Breadcrumbitems Title Pageactions Summarydetails Tabs**: If the control is set to `keepBreadcrumbAndTabs=true` then include the divider line between the breadcrumbs & tabs when they meet on scroll
![Artboard Copy 8](https://user-images.githubusercontent.com/50155706/99849724-af5e6600-2b41-11eb-888d-db5b8c7d84d2.png)
- [x] **With Background Breadcrumbitems Actionbar Title Pageactions Tabs Tags**: Slow down the duration of the button that animates into the breadcrumb bar on scroll. It's currently too fast. Try ~240-300ms

TODO:
- [x] Breadcrumb with overflow
- [x] ActionBarItems with overflow
- [x] Tags component not quite complete. (Alignment and show all)

## Questions

1. What size/type of "available content" filling can we have?

**Comment by lee-chase** [comment]
Marked as blocked as to the status of the design it was marked as 'status: refining' by @carrenelloyd

**Comment by cameroncalder** [comment]
# Overview info

## Anatomy

The page header is comprised of 6 zones, allowing for the flexibility to include (or exclude) areas depending on the context and needs of the page.

![image](https://user-images.githubusercontent.com/50155706/93520637-69dcad00-f8f4-11ea-8d2a-d56c90beb0b4.png)

1. **Breadcrumbs:** This zone is for the breadcrumb component to be displayed. Breadcrumbs should typically be displayed if there are navigable pages that precede the current page.
2. **Page title:** This zone is for a page title to be displayed. Optionally an icon can be included to the left of the title text.
3. **Subtitle / description (optional):** This zone is for the inclusion of a subtitle or description to provide additional context to identify the current page.
4. **Available space (optional):** This zone is for placing high-level content above page tabs.
5. **Tabs (optional):** This zone is for placing navigation within a page. e.g. tabs, content switcher etc.
6. **Actions (optional):** This zone is for placing critical page actions.

## Main types

### Page header without background
The simplest expression of the page header. A background-less page header should be used if only the breadcrumb, title, actions, and/or simple status are required.
![image](https://user-images.githubusercontent.com/50155706/93520751-9a244b80-f8f4-11ea-8bc1-88ddf84349ad.png)

### Page header with background
The more complex expression of the page header. The background provides structurality and aids in establishing hierarchy for page headers with more items. The page header with a background should be used if tabs, subtitles, and/or more global items are required.
![image](https://user-images.githubusercontent.com/50155706/93520842-baeca100-f8f4-11ea-8399-76ebc74606d9.png)

### Page header with background (breadcrumb + actions toolbar included)
If the page header contains action icons, the default state includes a toolbar designated for the breadcrumbs and action icons.
![image](https://user-images.githubusercontent.com/50155706/93521884-474b9380-f8f6-11ea-85ae-4c1160d88f1d.png)

### Page header with background (breadcrumb + actions toolbar ONLY)
On occasion, a condensed page header is required. This version accommodates this by just displaying the breadcrumb bar only.
![breadcrumb-bar-only](https://user-images.githubusercontent.com/50155706/93522454-19b31a00-f8f7-11ea-9798-5034317318f3.png)


## Examples

The page header should allow for the flexibility to additively contain both type and components w/ predictable spacing in the overall layout.

### Examples without background

#### Page title only
This is the base of the page header, establishing spacing/title structure that all other sans background page headers follow. The base is best used to accommodate simple requirements, including page title only, or page title + buttons.
![image](https://user-images.githubusercontent.com/50155706/93521467-ba083f00-f8f5-11ea-9767-8606ce499e03.png)

#### With breadcrumbs
This variant of the page header accounts for page title, buttons, breadcrumbs, and occasionally icons and metadata.
![image](https://user-images.githubusercontent.com/50155706/93521503-c42a3d80-f8f5-11ea-9611-d6c907bc4344.png)

#### With status indicator
Structured similarly to the examples above, this variant is for the inclusion of a page level status indicator.
![image](https://user-images.githubusercontent.com/50155706/93521520-c8eef180-f8f5-11ea-9271-4b098001b4bc.png)

### Examples with background

#### With tabs
Tabs are positioned underneath the page title and sit flush at the base of the page header background.
![image](https://user-images.githubusercontent.com/50155706/93521612-f045be80-f8f5-11ea-8dba-01f63259f759.png)

#### With tags
Tags are positioned underneath the page title and sit above the base of the page header background.
![image](https://user-images.githubusercontent.com/50155706/93521637-f8056300-f8f5-11ea-944a-f7c8a79a5c72.png)

#### With tabs & tags
If both tabs & tags need to be present, tabs should be remain left aligned with the page and tags reposition over to the right side of the screen.
![image](https://user-images.githubusercontent.com/50155706/93521653-fd62ad80-f8f5-11ea-96c1-60f33b0da20a.png)

#### With subtitle
Subtitles, if necessary, are placed directly below the page title. Page headers with subtitles use the background to create hierarchy and to separate it from type placed within the page.
![image](https://user-images.githubusercontent.com/50155706/93521676-05225200-f8f6-11ea-84ee-1dc5cc9f8f1b.png)

#### With summary details
Page content with global page hierarchy can be placed above tabs within the page header. **This is just an example of an allowable zone for content. The actual page content should be determined by the offering team.**
![image](https://user-images.githubusercontent.com/50155706/93521737-1b301280-f8f6-11ea-8637-6f876f70621a.png)

**Comment by cameroncalder** [comment]
# Structure

The page header delivers consistent spacing and uniform content placement. This avoids jarring movement and unexpected behavior when navigating within the offering and across the portfolio.

## Spacing

### Page header without background
#### No breadcrumb
![structure-title-only](https://user-images.githubusercontent.com/50155706/93525853-39007600-f8fc-11ea-9867-9ee26657611a.png)

#### With breadcrumb
![structure-title-breadcrumbs](https://user-images.githubusercontent.com/50155706/93525874-40278400-f8fc-11ea-8769-5526d2422583.png)

#### With status
![structure-status](https://user-images.githubusercontent.com/50155706/93525895-4584ce80-f8fc-11ea-84c7-b2eb8af60b8c.png)

### Page header with background

#### With tabs
![structure-tabs](https://user-images.githubusercontent.com/50155706/93526011-71a04f80-f8fc-11ea-95f8-10750063fed7.png)

#### With tabs & tags
![structure-tabs-tags](https://user-images.githubusercontent.com/50155706/93526159-a90efc00-f8fc-11ea-863a-e6cb0e9a4656.png)

#### With tags
![structure-tags](https://user-images.githubusercontent.com/50155706/93526175-b1673700-f8fc-11ea-814d-06fc1b23ecb0.png)

#### With subtitle
![structure-sub-title](https://user-images.githubusercontent.com/50155706/93526190-b75d1800-f8fc-11ea-942e-f34a20829aad.png)

#### With breadcrumb/actionbar
![structure-bar](https://user-images.githubusercontent.com/50155706/93526454-1884eb80-f8fd-11ea-9868-21887e3174cf.png)

### Page header with breadcrumb/actionbar only
![structure-bar](https://user-images.githubusercontent.com/50155706/93526478-1fabf980-f8fd-11ea-93c6-bb55e44be74f.png)



## Typography

Page titles and subtitles should be [sentence case](https://www.carbondesignsystem.com/guidelines/content/guidance/#use-sentence-case-capitalization), with only the first word and proper nouns capitalized.

![image](https://user-images.githubusercontent.com/50155706/93526547-381c1400-f8fd-11ea-9c18-f11f2b95a6d9.png)


|                 | Carbon token            | rem  | px |
|-----------------|-------------------------|------|----|
| Breadcrumbs     | `$label-01`             | .75  | 12 |
| Title           | `$productive-heading-04`| 1.75 | 28 |
| Subtitle        | `$body-long-02`         | 1    | 16 |

 

## Color 

The page header is available for both **gray 10** and **gray 100** themes.

### Gray 10 theme
![with-breadcrumbs](https://user-images.githubusercontent.com/50155706/93526647-597d0000-f8fd-11ea-87b0-24c67740cf23.png)
![page-header-with-background](https://user-images.githubusercontent.com/50155706/93526665-5e41b400-f8fd-11ea-99c1-e8e982684855.png)
![breadcrumb-bar-only](https://user-images.githubusercontent.com/50155706/93526676-639efe80-f8fd-11ea-9095-f682ff0bb364.png)

### Gray 100 theme
![with-breadcrumbs-100](https://user-images.githubusercontent.com/50155706/93526689-68fc4900-f8fd-11ea-9b0e-886cd8f59132.png)
![page-header-with-background-100](https://user-images.githubusercontent.com/50155706/93526704-6ef22a00-f8fd-11ea-8188-712c30e3cfd8.png)
![breadcrumb-bar-only-100](https://user-images.githubusercontent.com/50155706/93526712-73b6de00-f8fd-11ea-997f-b430fb584de7.png)

**Comment by cameroncalder** [comment]
# Scrolling behavior

#### Default
The page title scrolls with the rest of the page content. Once the page title scrolls out of view, the current page title appends to the end of the breadcrumbs.
![page-header-transition-1](https://user-images.githubusercontent.com/50155706/93526906-bc6e9700-f8fd-11ea-8762-91edf270c082.gif)


#### With button(s)
The button transition accompanies the default scrolling behavior. If a button or set of buttons is included in the page header, they should scroll with the page until they meet the base of the global header. The button(s) then stays in that position for the remainder of the page scroll. Scrolling back to the top of the page puts the transition in reverse.
![page-header-transition-2](https://user-images.githubusercontent.com/50155706/93526919-c0021e00-f8fd-11ea-9f45-6c9cd21cbe7d.gif)


#### With action toolbar + button(s)
If the page header includes a toolbar, the buttons scroll with the page next to the page title. As the buttons scroll out of view, they should fade in to view in the toolbar next to the actions.
*button fade-in & fade-out transition* = motion(entrance, productive) / cubic-bezier(0, 0, 0.38, 0.9) \$transition—base
![page-header-transition-3](https://user-images.githubusercontent.com/50155706/93526953-cbede000-f8fd-11ea-9182-f0199bbfc6c0.gif)


#### With tabs
The page title transition remains the same. After this initial transition, the tabs push the breadcrumbs out of view as the page is scrolled further. As soon as the page is scrolled towards the top, the breadcrumb row reveals again stacked above the tabs. Only again once the top of the page is reached on scroll does the full page header reveal.
![page-header-transition-4](https://user-images.githubusercontent.com/50155706/93526964-cf816700-f8fd-11ea-9988-fff29553b9bf.gif)

**Comment by cameroncalder** [comment]
# Page title lengths

### Character count
To maintain page titles that are efficient to read and avoid crowding within the page header, the title length should be no more than ~56 characters.
![image](https://user-images.githubusercontent.com/50155706/93528170-8c27f800-f8ff-11ea-8379-62ac8d3479b8.png)


### Truncation
Page titles should remain on a single line instead of wrapping to multiple lines. Use truncation for titles that must exceed the 56 character count and/or stages with narrow widths. If the titles become truncated, ensure browser tooltips over the page title are used on hover to display the full string.
![image](https://user-images.githubusercontent.com/50155706/93528181-90541580-f8ff-11ea-8d49-57b0b2d3202b.png)
![image](https://user-images.githubusercontent.com/50155706/93528189-934f0600-f8ff-11ea-8145-457542a2122b.png)

**Comment by lee-chase** [comment]
@cameroncalder in the animated designs tabs stay in view, but tags scroll off the top. What happens when both tags and tabs are displayed?

**Comment by cameroncalder** [comment]
Hey @lee-chase great question. In the case where there are both tabs & tags, lets keep the tags visible since they sit on the same row as the tabs. If it's just the tags though, they can scroll out of view

**Comment by SimonFinney** [comment]
See https://github.com/carbon-design-system/ibm-security/pull/685 for animation example

**Comment by lee-chase** [comment]
@SimonFinney Which story?

**Comment by lee-chase** [comment]
@cameroncalder icon buttons must have tooltip, should be positioned how?

Options are top left bottom and right with alignment to start, center or end.

e.g. Bottom End
![image](https://user-images.githubusercontent.com/15086604/94048522-89c81100-fdcb-11ea-923d-aeadfb00d9a9.png)

**Comment by lee-chase** [comment]
@cameroncalder are only field size buttons that neatly line up (almost*) line up with the title?

Or is the whole right side the height of breadcrumb, title and subtitle combined?

NOTE: Productive Headihg 4 has a line height of 36px and field buttons are 40px.

**Comment by cameroncalder** [comment]
Yeah as you noticed, to keep it vertically aligned with the page title, the field button ends up being an actual offset of 30 from the top... Other field buttons variants, or sets of side-by-side field buttons, could be used there as well. For instance, a field size ghost icon button acting as an overflow. Also, the total height of the page header is based on the left side content: spacers, the title, subtitle, and various other components (like tabs) that may be 'stacked'

**Comment by cameroncalder** [comment]
> @cameroncalder icon buttons must have tooltip, should be positioned how?
> 
> Options are top left bottom and right with alignment to start, center or end.
> 
> e.g. Bottom End
> ![image](https://user-images.githubusercontent.com/15086604/94048522-89c81100-fdcb-11ea-923d-aeadfb00d9a9.png)

Would be great to do 'Bottom Center' if space allows for the string. If not, 'Bottom End' would be favored. Esp for actions on  the far right side of the toolbar

**Comment by lee-chase** [comment]
@cameroncalder Not merged yet but this preview shows a very basic responsive behaviour. Below about px wide it starts to break down and may need reviewing with regard to structure and animation. 

https://deploy-preview-108--ibm-cloud-paks.netlify.app/?path=/story/experimental-pageheader--all-attributes-set

This is a slightly silly version as an example.

https://deploy-preview-108--ibm-cloud-paks.netlify.app/?path=/story/experimental-pageheader--long-values-and-many-items

While I realise some of the values should be truncated or restricted in some other way I thought you might want to take a look as is.

**Comment by lee-chase** [comment]
@cameroncalder What happens to the title on scroll if there is not breadcrumb?

**Comment by moores2** [comment]
@cameroncalder In this design for the PageHeader the primary action buttons are towards the top right of the screen and become sticky at the top of the screen when the page scrolls. However, an interim design for the create flows that I have seen now has primary action buttons bottom right (they appear to have moved to the bottom). Isn't this an inconsistency? Could you confer with Andrew Smith and clarify this please?

**Comment by cameroncalder** [comment]
> @cameroncalder What happens to the title on scroll if there is not breadcrumb?

@lee-chase the page title should just scroll out of view and not appear in the breadcrumb row

**Comment by cameroncalder** [comment]
> @cameroncalder In this design for the PageHeader the primary action buttons are towards the top right of the screen and become sticky at the top of the screen when the page scrolls. However, an interim design for the create flows that I have seen now has primary action buttons bottom right (they appear to have moved to the bottom). Isn't this an inconsistency? Could you confer with Andrew Smith and clarify this please?

Hey @moores2 Appreciate the check on this. Andrew was actually a collaborating partner on this page header as well. The buttons in 'create flows' are reserved for pagination/confirmation and sit at the bottom as they follow the top-down content/form completion necessary to progress forward. The bottom placement in 'create flows' also drives consistency in the placement of like experiences across other components, like modals & tearsheets. The action buttons within the page header should be thought of high-level page actions. And actions that initiate something, rather than confirm or paginate. That's the distinction

**Comment by moores2** [comment]
@cameroncalder Thanks for the confirmation that difference is intentional.

**Comment by cameroncalder** [comment]
Responsive behavior examples

1312
![1312 breakpoint example](https://user-images.githubusercontent.com/50155706/94694685-b5cb2100-02fa-11eb-9168-abc4433039d6.png)

1056
![1056 breakpoint example](https://user-images.githubusercontent.com/50155706/94694727-bebbf280-02fa-11eb-92cc-bb120e8a2ec6.png)

672
![672 breakpoint example](https://user-images.githubusercontent.com/50155706/94694756-c67b9700-02fa-11eb-9a93-d86b52c9ca09.png)

320
![320 breakpoint example](https://user-images.githubusercontent.com/50155706/94694771-cb404b00-02fa-11eb-9130-ce95ac3a41e5.png)


Follows Carbon breadcrumb overflow guidance (one path at the front and two at the end, space providing)
https://www.carbondesignsystem.com/components/breadcrumb/usage/#overflow-content

_*Note, CP4S use-case: For breadcrumbs requiring overflow, two paths are placed at the front of the breadcrumb and one at the end because of the nature of the application IA in relation to the platform. This provides a quick path back to the root of the current application in addition to the platform homepage)_

**Comment by lee-chase** [comment]
@cameroncalder The page action area. Does this only contain field sized buttons? If so we should probably only allow the user to pass config for the buttons as opposed to actual buttons

**Comment by lee-chase** [comment]
@cameroncalder we have included status in the 'available space' section is that what. you intended?

**Comment by cameroncalder** [comment]
> @cameroncalder The page action area. Does this only contain field sized buttons? If so we should probably only allow the user to pass config for the buttons as opposed to actual buttons

Yeah, we'd want teams to stick with the field sized buttons in that zone but it could be any type of button or group of buttons passed through

**Comment by cameroncalder** [comment]
> @cameroncalder we have included status in the 'available space' section is that what. you intended?

The 'available space' section should be used only with a page header that includes the background. The 'status' is the limit of stacked objects that can be used with the background-less page header. Is it structured in a manner that supports the inclusion of an 'available space' section independent of a page header with or without a background?

**Comment by lee-chase** [comment]
@cameroncalder can you start to review against the design. When you find a fault please create a checkbox list in a comment and I will append it ToDo list.

**Comment by moores2** [comment]
@cameroncalder It turns out that truncating titles over 56 chars to 55 chars + an ellipsis is hard to do in a culturally correct way, for 2 reasons:
1. You really need to truncate on a word boundary to avoid having a part word at the end of the line that might be offensive or confusing. This is really hard to do in languages like Chinese where the are no breaks (e.g. spaces) between words. In that case deciding which glyphs belong to which words needs a dictionary lookup I believe.
2. Not every language uses the same ellipsis - Chinese has 6 dots I think, and Japanese anything from 1 to 4, for example.

So, as an alternative, since the title is one line only can we use the standard CSS functionality of `text-overflow: ellipsis` to truncate and add an ellipsis when the text is too long for the available space? We would need to decide what the max length of the title is in px or % width of the header etc, but then the string would truncate when it exceeded that, not based on a specific number of characters. This would give the added advantage that it's a responsive solution that adapts as the width available for the title changes, and not fixed at 56 chars.  

Thoughts?

**Comment by lee-chase** [comment]
@cameroncalder $transition—base is not listed as a valid token on the carbon design system website.  https://www.carbondesignsystem.com/guidelines/motion/overview#duration-tokens

In the carbon source code it is initially set to 250ms but updated to $duration--fast-02 (110ms). I have made use of the $duration--fast-02 token.

**Comment by lee-chase** [comment]
@moores2 @cameroncalder 
1. The divider under the breadcrumb/actionbar looks weird full width of the screen. Is this really a requirement?
2. With so many moving parts spacing is tricky. If there is an error please point out the specific case.
3. 'With Background BreadcrumbItems and Actionbar' - "Should include page title". No title is specified, but if one were it would initially be below the breadcrumbs. Are we saying that in the case where only breadcrumb and title row are specified we should pre-collapse into breadcrumb?

**Comment by cameroncalder** [comment]
> @moores2 @cameroncalder
> 
> 1. The divider under the breadcrumb/actionbar looks weird full width of the screen. Is this really a requirement?

Hey, yes it should go the full width of the screen

> 2. With so many moving parts spacing is tricky. If there is an error please point out the specific case.

I'll go through the variants tomorrow and specify which should be addressed

> 3. 'With Background BreadcrumbItems and Actionbar' - "Should include page title". No title is specified, but if one were it would initially be below the breadcrumbs. Are we saying that in the case where only breadcrumb and title row are specified we should pre-collapse into breadcrumb?

Yeah, in [cases like this](https://ibm-cloud-paks.netlify.app/?path=/story/experimental-pageheader--with-background-breadcrumbitems-actionbar) where it's pre-collapsed it would show the title at the end of the breadcrumb 👍

**Comment by lee-chase** [comment]
@cameroncalder's additional notes on spacing

![image](https://user-images.githubusercontent.com/15086604/96692909-8732ea00-137e-11eb-8a98-c0b2d730160c.png)

**Comment by lee-chase** [comment]
In discussion with @cameroncalder agreed

- Content switcher should scroll off same as tabs
- line under breadcrumb with action bars should be full width
- action bar items should be far right (of page)
- noted content switcher background issue (due to change of header background color).
- An option to keep both tabs and breadcrumb row would be nice
- Noted title in the 'With background & action bar' is missing a title and margin bottom when added.
- Agreed on a switch to pre-collapse title, breadcrumbs, action bar items and page actions.

**Comment by lee-chase** [comment]
Review notes (@lee-chase, @moores2 and @cameroncalder).

- Story 'With Background Breadcrumbitems Title Pageacations Content Swither' has an issue on scroll. (Page actions scroll half off).
- Breadcrumbs - When more than 3 + title use overflow https://www.carbondesignsystem.com/components/breadcrumb/usage/#overflow-content
- Title should be allowed 60% width before ellipses on larger screens. No character limit user browser behaviour for ...
- Title should be two lines before ellipsis on mobile sizes (< 768 iPad portrait)
- Primary action buttons should not wrap, use overflow menu if more than 2. Maybe a case for documenting a limit? @cameroncalder to investigate.
- Tabs should not be limited to less than 75% width by tags. With no tags, they can be 100%.
- Tags should use #32 additional tag pattern if more than 25%. NOTE: In lieu of #32 a tooltip will be used.
- @cameroncalder to provide a long content example
- @cameroncalder to provide further detail on responsive/mobile size.

**Comment by lee-chase** [comment]
@cameroncalder note: We do not currently add pageActionButtons directly, they are supplied by the user. We could change the API to have the user pass just config for buttons giving us more control over the number and nature of buttons rendered.

**Comment by cameroncalder** [comment]
@lee-chase @moores2 

Here's a reference for the '[Long values and many items](https://deploy-preview-152--ibm-cloud-cognitive.netlify.app/?path=/story/experimental-pageheader--long-values-and-many-items)' example
![Page header with optional content](https://user-images.githubusercontent.com/50155706/97358755-b27b7480-1869-11eb-82db-992c231acc9f.png)

**Comment by cameroncalder** [comment]
Spacing update to account for the existing margins around the tags
![Complex page header (tag placement option)-40bar Copy 22](https://user-images.githubusercontent.com/50155706/97358933-fc645a80-1869-11eb-94b2-f743f1319454.png)

**Comment by lee-chase** [comment]
Blocked: 
- Waiting on a carbon update to be released with Tooltip align (10.25.0 which appears imminent).
- Also needs ActionBarItems overflow

**Comment by cameroncalder** [comment]
@lee-chase spacing I mentioned during our sync. `spacing-02` is the correct spacing between the breadcrumb and title in all instances except when there is a breadcrumb/actionbar
![image](https://user-images.githubusercontent.com/50155706/106958317-d10dc900-66fe-11eb-9ae0-3ffe282e10ab.png)

**Comment by cameroncalder** [comment]
Manual expand/collapse reference images

![page header 10 manual expanded](https://user-images.githubusercontent.com/50155706/106958880-922c4300-66ff-11eb-862e-c322647b0fb5.png)
![page header 10 manual collapsed](https://user-images.githubusercontent.com/50155706/106958894-96586080-66ff-11eb-861f-71aecad6cd4e.png)

**Comment by cameroncalder** [comment]
Link to Sketch file: https://ibm.box.com/s/tb0e5r5dh3zwbjvwp5081yr3lq6vfony

**Comment by lee-chase** [comment]
> @lee-chase spacing I mentioned during our sync. `spacing-02` is the correct spacing between the breadcrumb and title in all instances except when there is a breadcrumb/actionbar
> ![image](https://user-images.githubusercontent.com/50155706/106958317-d10dc900-66fe-11eb-9ae0-3ffe282e10ab.png)

Addressed in in #321

**Comment by lee-chase** [comment]
> Manual expand/collapse reference images
> 
> ![page header 10 manual expanded](https://user-images.githubusercontent.com/50155706/106958880-922c4300-66ff-11eb-862e-c322647b0fb5.png)
> ![page header 10 manual collapsed](https://user-images.githubusercontent.com/50155706/106958894-96586080-66ff-11eb-861f-71aecad6cd4e.png)

@cameroncalder where does the chevron go if there are no tabs/tags?

**Comment by lee-chase** [comment]
Unblocked as a result of #329

**Comment by cameroncalder** [comment]
Amazing work @lee-chase 🙌 Page header component LGTM! 🚀

**Comment by lee-chase** [comment]
Design review #897

**Comment by dcwarwick** [comment]
release review completed and delivered with #1072
