### ISSUE TITLE
Side panel

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#64]
Catalog # 21

[Link to Design ](https://pages.github.ibm.com/cdai-design/pal/components/slide-in-panel/)

See also
https://pages.github.ibm.com/ibmcloud/pal/components/side-panel/usage/

## Tasks

- [x] Initial review of design/existing code

### Working in experimental package

- [x] Create a shell component which
  - [x] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [x] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [x] Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.
- [x] First engineering review/playback

### Continuing in experimental package

- [x] Storybook - stories to cover design scenarios, story with long, min and
      max content, etc
- [x] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [x] Code to include prop-types with comments for automated DocGen
      documentation
- [x] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

### Review and promote

- [x] Design review
- [x] Add design review issues addressed, issues raised or discounted.
- [x] Engineering review - Submit PR to promote component to production package
- [x] All engineering issues addressed, issues raised or discounted.

**Comment by lee-chase** [comment]
Blocked as the status of the design it was set to 'status: refining' by @carrenelloyd

**Comment by vikkidpaterson** [comment]
@carrenelloyd what was the reason behind the refining status tag - do you have a link to anything around the refinements underway?

**Comment by lee-chase** [comment]
@gatfora @carrenelloyd wondering what the state of the design is here?

**Comment by Levinson1** [comment]
Design is complete and published
https://pages.github.ibm.com/cdai-design/pal/components/side-panel/usage

**Comment by andrea-gm** [comment]
@matthewgallo will meet with the design owner Kacie to get design approval

**Comment by andrea-gm** [comment]
@matthewgallo can you provide an update from your meeting with Kacie?

**Comment by matthewgallo** [comment]
Yes definitely, here are some of my notes:
```
1. Margin right on title increase to $spacing-07
2. Add `title` html attribute to title in side panel
3. Add underline to bottom of fixed section (1px solid $decorative)
4. Allow size of panel to be controlled by Storybook controls
5. Add optional labelText prop with label-01 type token
   - bottom padding $spacing-02
  ```

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/731 --> will add multi step capability

**Comment by matthewgallo** [comment]
## Review for release

### Readiness

- [ ] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [ ] A functioning component or components delivering those scenarios have been delivered and merged to master.
- [ ] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [ ] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [ ] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [ ] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [ ] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [ ] Components are functional components using hooks.
- [ ] Public components which produce DOM structures support className.
- [ ] Public components support a ref (via React.forwardRef).
- [ ] All significant DOM elements have meaningful classes.
- [ ] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [ ] No warnings, errors or log messages in the console.
- [ ] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js.

### Standards

- [ ] No linter warnings or errors are produced.
- [ ] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [ ] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [ ] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [ ] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [ ] There is a set of test cases for the components.
- [ ] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [ ] The tests validate the behaviors and interactions defined in the design where practical.
- [ ] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [ ] No warnings, errors or log messages in the test output.

### Documentation

- [ ] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [ ] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [ ] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by matthewgallo** [comment]
This component has been released. Anything that comes up can be tracked in new issues
