### ISSUE TITLE
User profile images

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#69]
Catalog # 27

[Link to Design ](https://pages.github.ibm.com/cdai-design/pal/patterns/user-profile-images/)

**Maintainers**
Marion Brülls

## Tasks

- [x] Initial review of design/existing code

### Working in experimental package

- [x] Create a shell component which
  - [x] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [x] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [x] Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.
- [ ] First engineering review/playback

### Continuing in experimental package

- [ ] Storybook - stories to cover design scenarios, story with long, min and
      max content, etc
- [ ] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [ ] Code to include prop-types with comments for automated DocGen
      documentation
- [ ] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

### Review and promote

- [ ] Design review
- [ ] Add design review issues addressed, issues raised or discounted.
- [ ] Engineering review - Submit PR to promote component to production package
- [ ] All engineering issues addressed, issues raised or discounted.

**Comment by lee-chase** [comment]
Blocked as the status of the design it was set to 'status: refining' by @carrenelloyd

Invited Marion Brülls to join the conversation here.

**Comment by Levinson1** [comment]
Design completed and live

**Comment by lee-chase** [comment]
Dev thoughts.

Would 'Avatar' be a better name for the component? Calling it UserProfileImage may discourage group use and strictly speaking it may not be an image.

**Comment by lee-chase** [comment]
2. IBM Profiles ask the user to provide
- First name
- Inital (optional)
- Last name
-Display name

Would it not be better to use the first two capitalized letters should be used from the display name.

**Comment by qbi11y** [comment]
@lee-chase @carrenelloyd who do I need to speak with to come up to speed on this issue?

**Comment by andrea-gm** [comment]
@qbi11y, Marion Brulls and Mitchell Bernstein (wish I could tag them...) own the pattern, but it is currently under discussion with Carmen Darlach for the dark/light theme switching, to determine what the behavior should be for light versus dark theme (map to lighter colors OR a white border around the circle). I've reached out to Carmen and will report back on what the decision is for the pattern. This decision will affect the CSS, but probably not much else.

**Comment by lee-chase** [comment]
Personally don’t like dark/light theme switches and think we should switch automatically based on theme. Unfortunately, it is only possible to take a best guess at the current Carbon theme based on the value of the background color.

**Comment by marion-bruells** [comment]
Copying from our slack conversation:

Marion: 
To your question @lee-chase : 
```
IBM Profiles ask the user to provide
First name
Inital (optional)
Last name
Display name
Would it not be better to use the first two capitalized letters should be used from the display name.
```

We originally designed it with first and last name – how users also know from box and other applications. I know some applications use also the display name. What benefits are you seeing in using the display name instead on our platforms?

Lee: I felt the need to point out what is asked for elsewhere. If a display name is given I would expect it to be used over the users name.

**Comment by marion-bruells** [comment]
@lee-chase If display name is elsewhere used over the users name I am ok to follow also that path.

**Comment by qbi11y** [comment]
@marion-bruells @lee-chase @andrea-gm I have run into an issue where the design calls for a size (64px) that Carbon does not support. Is this 64px only for profile images or should it be applied to icons and initials as well?

In regards to font size, the design calls for 8 and 10px. The lowest carbon support is a 12px token. Is there a plan for Carbon to support these lower sizes or should the implementation ignore Carbon token support and force the 8 and 10px sizes?

Responding to the display name conversation. My assumption is the component consumer would pass the entire display name to the component and the component would need to format the display name to fit in the display circle. Is this assumption correct?

**Comment by lee-chase** [comment]
@qbi11y `$spacing-10` and `$container-05` are undocumented 64px. `$layout-05` is also 64px.

**Comment by qbi11y** [comment]
@lee-chase @andrea-gm this is ready for an initial engineering review. Please advise on how to proceed.

**Comment by andrea-gm** [comment]
@qbi11y I can do an initial review. I'll schedule some time for us tomorrow (Monday)!

**Comment by matthewgallo** [comment]
## Review for release

### Readiness

- [ ] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [ ] A functioning component or components delivering those scenarios have been delivered and merged to master.
- [ ] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [ ] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [ ] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [ ] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [ ] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [ ] Components are functional components using hooks.
- [ ] Public components which produce DOM structures support className.
- [ ] Public components support a ref (via React.forwardRef).
- [ ] All significant DOM elements have meaningful classes.
- [ ] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [ ] No warnings, errors or log messages in the console.
- [ ] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js.

### Standards

- [ ] No linter warnings or errors are produced.
- [ ] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [ ] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [ ] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [ ] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [ ] There is a set of test cases for the components.
- [ ] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [ ] The tests validate the behaviors and interactions defined in the design where practical.
- [ ] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [ ] No warnings, errors or log messages in the test output.

### Documentation

- [ ] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [ ] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [ ] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by qbi11y** [comment]
@marion-bruells can you please review the component from a design perspective: https://ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-canary-userprofileimage--default

**Comment by marion-bruells** [comment]
I reviewed in the storybook and I found some accessibility issues. Here is my feedback:

- Text and icon color on light colors should be dark instead of white for sequence 30 and 50 to ensure accessibility (color contrast ratio).
Current implementation:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/51152537/115533776-5aad4b80-a297-11eb-82a0-9a24e20dd9df.png">
Please check again based on to those guidelines: 
To-be:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/51152537/115533868-787ab080-a297-11eb-9d34-5b640cf3f831.png">

- We should get rid of the sizes sm and xs. The text and icon is not fitting in that size also I wonder if an icon really should be used in that size. Mitchell and I have to update this in the guidance. Seeing this implemented it isn’t accessible enough in that size. Text and icon is too squeezed.
Current implementation:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51152537/115533520-15891980-a297-11eb-9a92-59f8a5b5696c.png">
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/51152537/115533592-29348000-a297-11eb-894b-d55d804fba21.png">
To-be: remove xs and sm size - we should only support 64px (xl), 32px (lg), 24px (md)

- Add alt-text, if used as image-only to ensure accessibility (screenreader). Text should be the user or group’s display name. 
We have two use cases here:
1. When we only display the image in the UI (without a full text string next to it): Here we have to add descriptive alt-text to the image. I suggest that in this case the user also can hover on the image to see the full string (user or group’s display name) in a tooltip.
<img width="306" alt="image" src="https://user-images.githubusercontent.com/51152537/115537274-f3919600-a29a-11eb-8a5d-5b70604d8f1a.png">

2. In cases where a text label is in addition to the image in the UI, it doesn’t require this - here the screenreader just reads the text next to it and the user doesn’t require a tooltip on hovering the image either, as the name is placed next to it already. Having alt-text in addition here would just repeat the same meaning - which can be annoying. 
<img width="378" alt="image" src="https://user-images.githubusercontent.com/51152537/115536969-9f86b180-a29a-11eb-8b0d-921d25425de0.png">

We should consider this two use cases and support this alt-text for 1 - but make sure it can be disabled for case 2.

**Comment by qbi11y** [comment]
@marion-bruells I removed the small sizes as asked. As far as the text color. Since we are unable to detect the theme, the dev needs to pass the theme into the component. If you didn't update the theme switcher and the theme control on the component would not display correctly in storybook. If you want to see how the component looks on the dark theme, set the theme to 'dark' on the component controls tab and also set it to dark on the theme switcher tab. You should then see the correct colors. 

In regards to the tooltip. I see there is conversation about the tooltip component vs browser tooltip. I have currently added the browser tooltip. It's not as visually appealing as the component but it sounds to me it is the best option. If you would like to switch to the component please let me know.

**Comment by dcwarwick** [comment]
Closed by #758
