### ISSUE TITLE
Web terminal

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#70]
Catalog # 28

[Link to Design ](https://pages.github.ibm.com/cdai-design/pal/patterns/web-terminal/)

**Maintainers**
Marcie Corral 
Courtney Banning

## Tasks

- [x] Initial review of design/existing code

### Working in experimental package

- [x] Create a shell component which
  - [x] Create ComponentName/ComponentName.js component file that renders props
        in raw form (no styling or sub components, plain text OK)
  - [x] Adds prop-types with comments for DocGen to
        ComponentName/ComponentName.js
  - [x] Add Doc file e.g. ComponentName.mdx with a brief description of the
        component.
- [ ] First engineering review/playback

### Continuing in experimental package

- [x] Storybook - stories to cover design scenarios, story with long, min and
      max content, etc
- [x] Doc tab in storybook derived from design docs with embedded stories where
      appropriate
- [x] Code to include prop-types with comments for automated DocGen
      documentation
- [ ] Tests (written in React Test Library) to cover behavior from the
      documented in the components mdx file.

### Review and promote

- [ ] Design review
- [ ] Add design review issues addressed, issues raised or discounted.
- [ ] Engineering review - Submit PR to promote component to production package
- [ ] All engineering issues addressed, issues raised or discounted.

**Comment by marciecorral** [comment]
This was designed for MCM about a year ago, by a designer no longer at IBM. Hoping to discuss today on the call if we have time.

**Comment by marciecorral** [comment]
Alexander.Melo@ibm.com is a FED on our team and he is familiar with this design and willing to help code this. I mentioned this to David L. today, so will follow up with any plan.

**Comment by AlexanderMelox** [comment]
I can go ahead and work on this

**Comment by AlexanderMelox** [comment]
Is there an Invision Link for this prototype?

**Comment by Levinson1** [comment]
Courtney Banning worked on this one and has provided an Invision link
https://ibm.invisionapp.com/share/GXNZTC9F83B

**Comment by AlexanderMelox** [comment]
One concern I have while working on this is how are we going to handle the terminal part of it? Would we just allow the developer to pass their own Terminal component that way it's not opiniated?

**Comment by AlexanderMelox** [comment]
I am currently working on this issue and should have it done within 2 weeks. Can we remove the stale status so the issue does not get archived?

**Comment by AlexanderMelox** [comment]
Status update showed the designer some things that were off like the colors weren’t carbon colors. And we had to reduce some of the features (which will later be in another issue to enhance the web terminal). Should be getting a PR in by end of week.

**Comment by AlexanderMelox** [comment]
Dropping this here for future reference. Lots of good questions here.

https://github.ibm.com/CloudIntegrationDesign/DesignSystemAdoptionGuild/issues/91
