### ISSUE TITLE
Cascading Card Wrapper

### ISSUE THREAD

**Issue by skcele** [carbon-design-system/ibm-cloud-cognitive#911]
# Name of component or pattern
Cascading Card Wrapper

This component is part of the C&CS Micro-interactions project with Andrew Smith.

## Brief description

This wrapper will add cascading card motion (fade in one at a time) for cards or tiles placed within the wrapper. Ideally we will also make it available for those within a grid.

## Details
Design example: https://ibm.box.com/shared/static/9mo3tk3d5k9oqagvraw5jisms4gecljx.gif

Prototype with no grid: https://codepen.io/stephaniecree/pen/abJBzEJ
This works best if you resize the window to see them on separate rows too.

Existing motion within the Grid Layout in Cloud PAL, which we will pull from: https://pages.github.ibm.com/ibmcloud/pal/layouts/grid-layout/code#dashboard-with-motion
You can type spaces into the codebox below the demo to see the motion.

## Design Maintainer(s)

Stephanie Cree is main design maintainer, and Lisa Kaiser is a second contact.

We are working with @davidmenendez on this project!

## Tasks

Before starting work on this epic, please review and complete the following.

- [x] Initial review of design/existing code

Review has been done with the C&CS Microinteractions team, happy to do another if needed.

### Working in Cloud and Cognitive package

- [x] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [x] Have you noted our
      [reviewer guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/REVIEWERS_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component? -  David and I will be working on this next.

**Comment by davidmenendez** [comment]
Thanks for opening an issue 👍

**Comment by davidmenendez** [comment]
ok i have a basic implementation on my end that's set up based on the demo code you provided. this could possibly be expanded to integrate grid functionality, but i'll need to think the implementation through a bit more. i'll post a link shortly.
